#!/bin/bash

# 🏫 SchoolGPT Setup Script
# This script helps schools set up their SchoolGPT deployment quickly

echo "🏫 Welcome to SchoolGPT Setup!"
echo "================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}❌ Azure CLI is not installed${NC}"
    echo "Please install Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}❌ Terraform is not installed${NC}"
    echo "Please install Terraform: https://www.terraform.io/downloads.html"
    exit 1
fi

# Check if logged into Azure
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}⚠️  Not logged into Azure${NC}"
    echo "Please run: az login"
    exit 1
fi

echo -e "${GREEN}✅ Prerequisites check passed!${NC}"
echo ""

# Get Azure information
echo "🔍 Gathering Azure information..."
SUBSCRIPTION_ID=$(az account show --query id --output tsv)
TENANT_ID=$(az account show --query tenantId --output tsv)
OBJECT_ID=$(az ad signed-in-user show --query id --output tsv)

echo -e "${BLUE}Azure Subscription ID:${NC} $SUBSCRIPTION_ID"
echo -e "${BLUE}Azure Tenant ID:${NC} $TENANT_ID"
echo -e "${BLUE}Your Object ID:${NC} $OBJECT_ID"
echo ""

# Get school information
echo "🏫 School Information Setup"
echo "Please provide your school's information:"
echo ""

read -p "School Name (e.g., 'Lincoln Elementary'): " SCHOOL_NAME
read -p "IT Admin Email (e.g., 'tech@lincoln.edu'): " ADMIN_EMAIL
read -p "Azure Region (e.g., 'uksouth', 'eastus'): " AZURE_REGION

echo ""
echo "🔧 Resource Naming (must be globally unique)"
echo "Tip: Use your school's abbreviation to ensure uniqueness"
echo ""

read -p "Resource Group Name (e.g., 'lincoln-ai-rg'): " RG_NAME
read -p "AI Foundry Name (e.g., 'lincoln-ai-foundry'): " AI_FOUNDRY_NAME
read -p "AI Foundry Subdomain (e.g., 'lincoln-ai'): " AI_SUBDOMAIN
read -p "Container Registry Name (e.g., 'lincolnacr'): " ACR_NAME
read -p "Web App Name (e.g., 'lincoln-ai-app'): " WEB_APP_NAME
read -p "SQL Server Name (e.g., 'lincoln-ai-sql'): " SQL_SERVER_NAME
read -p "Key Vault Name (e.g., 'lincoln-ai-kv'): " KEY_VAULT_NAME

echo ""
read -s -p "SQL Admin Password (must be strong): " SQL_PASSWORD
echo ""

# Create terraform.tfvars from template
echo ""
echo "📝 Creating terraform.tfvars file..."

cat > infra/terraform.tfvars << EOF
#################################################################
# School Safe AI App - Configuration for $SCHOOL_NAME
# Generated by setup script on $(date)
#################################################################

# Azure Subscription & Tenant Information
azure_subscription_id = "$SUBSCRIPTION_ID"
azure_tenant_id       = "$TENANT_ID"

# School Configuration
school_name = "$SCHOOL_NAME AI Assistant"
alert_email = "$ADMIN_EMAIL"
location    = "$AZURE_REGION"

# Resource Naming
resource_group_name   = "$RG_NAME"
ai_foundry_name      = "$AI_FOUNDRY_NAME"
ai_foundry_subdomain = "$AI_SUBDOMAIN"
acr_name             = "$ACR_NAME"
web_app_name         = "$WEB_APP_NAME"
sql_server_name      = "$SQL_SERVER_NAME"
key_vault_name       = "$KEY_VAULT_NAME"

# Administrator Configuration
sql_azuread_admin_login     = "$ADMIN_EMAIL"
sql_azuread_admin_object_id = "$OBJECT_ID"
key_vault_admin_object_id   = "$OBJECT_ID"

# Security Configuration
sql_password = "$SQL_PASSWORD"

# AI Model Configuration (recommended defaults)
azure_openai_model                  = "gpt-35-turbo"
azure_openai_model_version          = "1106"
azure_openai_model_deployment_name  = "school-safe-chat"
model_sku_name                      = "Standard"
model_capacity                      = 120

# Performance Configuration (medium school)
app_service_sku = "B2"
sql_sku_name    = "S1"

# Application Configuration
app_service_plan_name = "${RG_NAME%-rg}-asp"
sql_db_name          = "schoolgptdb"
app_insights_name    = "${RG_NAME%-rg}-ai"
docker_image         = "schoolgpt-app"
docker_tag           = "latest"
acr_login_server     = "${ACR_NAME}.azurecr.io"
EOF

echo -e "${GREEN}✅ terraform.tfvars created successfully!${NC}"
echo ""

# Ask if user wants to deploy now
echo "🚀 Ready to deploy?"
echo "The following will be created:"
echo "  - Resource Group: $RG_NAME"
echo "  - AI Foundry: $AI_FOUNDRY_NAME"
echo "  - Web App: $WEB_APP_NAME"
echo "  - SQL Server: $SQL_SERVER_NAME"
echo "  - And 16 other Azure resources..."
echo ""

read -p "Deploy now? (y/N): " DEPLOY_NOW

if [[ $DEPLOY_NOW =~ ^[Yy]$ ]]; then
    echo ""
    echo "🚀 Starting deployment..."
    echo "This will take approximately 10-15 minutes."
    echo ""
    
    cd infra
    
    echo "🔧 Initializing Terraform..."
    terraform init
    
    echo ""
    echo "📋 Planning deployment..."
    terraform plan
    
    echo ""
    read -p "Continue with deployment? (y/N): " CONFIRM_DEPLOY
    
    if [[ $CONFIRM_DEPLOY =~ ^[Yy]$ ]]; then
        echo ""
        echo "🚀 Deploying infrastructure..."
        terraform apply -auto-approve
        
        if [ $? -eq 0 ]; then
            echo ""
            echo -e "${GREEN}🎉 Deployment completed successfully!${NC}"
            echo ""
            echo "📋 Next Steps:"
            echo "1. Configure GitHub Actions (see DEPLOYMENT_GUIDE.md)"
            echo "2. Push code to trigger app deployment"
            echo "3. Configure authentication (see app URL for instructions)"
            echo ""
            echo "📊 Deployment Summary:"
            terraform output deployment_summary
        else
            echo -e "${RED}❌ Deployment failed. Check errors above.${NC}"
            exit 1
        fi
    else
        echo "Deployment cancelled. You can deploy later with:"
        echo "  cd infra && terraform apply"
    fi
else
    echo "Configuration saved. You can deploy later with:"
    echo "  cd infra"
    echo "  terraform init"
    echo "  terraform plan"
    echo "  terraform apply"
fi

echo ""
echo -e "${GREEN}🏫 SchoolGPT setup completed!${NC}"
echo "📖 See DEPLOYMENT_GUIDE.md for detailed instructions"
echo "🤝 Need help? Visit: https://github.com/your-repo/schoolgpt" 