name: 🚀 03 - Deploy SchoolGPT SQL DACPAC

on:
    workflow_dispatch:

jobs:
  deploy-dacpac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install SqlPackage as a dotnet global tool
      - name: Install SqlPackage
        run: |
          dotnet tool install -g microsoft.sqlpackage
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Deploy DACPAC to Azure SQL
      - name: Publish DACPAC to Azure SQL
        run: |
          SqlPackage \
            /Action:Publish \
            /SourceFile:"./SQL/DAC/schoolsafegpt.dacpac" \
            /TargetServerName:"school1sqlsrvca30.database.windows.net" \
            /TargetDatabaseName:"schoolgptdb" \
            /TargetUser:"sqladminuser" \
            /TargetPassword:"MyStrongP@ssw0rd123!" \
            /p:BlockOnPossibleDataLoss=false \
            /p:DropObjectsNotInSource=false
