name: 🚀 Deploy AI Foundry Bicep

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: "Target Azure Resource Group"
        type: string
        default: "school-safe-gpt-rg"
        required: true
      location:
        description: "Azure region for the RG (e.g., westeurope)"
        type: string
        default: "UkSouth"
      aiFoundryName:
        description: "Azure AI Foundry (Cognitive Services) account name"
        type: string
        default: "school-safe-gpt-AI-Foundry-002"
        required: true
      aiProjectName:
        description: "Foundry project name"
        type: string
        required: true
        default: "school-safe-gpt-AI-Project-002"
      raiPolicyName:
        description: "RAI policy name"
        type: string
        default: "school-safe-GPT-high-filter-002"
        

permissions:
  id-token: write
  contents: read

env:
  BICEP_FILE: ./infra/AI-Foundry/main.bicep

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: Deploy Resource Group via CLI
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #           az group create --name School-Safe-GPT-RG-001 --location uksouth

      - name: Validate (debug)
        run: |
          az deployment group validate \
            --resource-group School-Safe-GPT-RG-002 \
            --template-file ./infra/AI-Foundry/main.bicep \
            --parameters location=uksouth aiFoundryName=school-safe-gpt-AI-Foundry aiProjectName=school-safe-gpt-AI-Project raiPolicyName=school-safe-GPT-high-filter \
            --output jsonc --verbose --debug

      - name: Deploy Bicep
        id: deploy
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: "School-Safe-GPT-RG-002"
          template: ${{ env.BICEP_FILE }}
          deploymentName: aifoundry-${{ github.run_number }}
          parameters: >
            location="uksouth"
            aiFoundryName=${{ github.event.inputs.aiFoundryName }}
            aiProjectName=${{ github.event.inputs.aiProjectName }}
            raiPolicyName=${{ github.event.inputs.raiPolicyName }}

      - name: Show Outputs
        run: |
          echo "AI Account ID:       ${{ steps.deploy.outputs.aiAccountId }}"
          echo "Project ID:          ${{ steps.deploy.outputs.projectId }}"
          echo "RAI Policy ID:       ${{ steps.deploy.outputs.raiPolicyId }}"
          echo "RAI Policy Name Out: ${{ steps.deploy.outputs.raiPolicyNameOut }}"
