name: Z01 - Print GitHub Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      KEY_VAULT_ADMIN_OBJECT_ID: ${{ secrets.KEY_VAULT_ADMIN_OBJECT_ID }}

    steps:
      - name: Print all selected secrets
        shell: bash
        run: |
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"
          echo "AZURE_CREDENTIALS=$AZURE_CREDENTIALS"
          echo "AZURE_TENANT_ID=$AZURE_TENANT_ID"
          echo "AZURE_WEBAPP_PUBLISH_PROFILE=$AZURE_WEBAPP_PUBLISH_PROFILE"
          echo "KEY_VAULT_ADMIN_OBJECT_ID=$KEY_VAULT_ADMIN_OBJECT_ID"
